postman:
  host: "{{calendar-url}}"
  exclude-paths:
    - /
    - /errors
  headers:
    Content-Type: application/json
    Authorization: "Bearer {{access-token}}"
  placeholders:
    squadId: squad-id
  request-wrapper:
    - path: /squads/**
      type: all
      headers:
        X-Squad-Id: "{{squad-id}}"